import streamlit as st
import spacy

# Load the language model
nlp = spacy.load("en_core_web_sm")

st.title("SpaCy Text Analysis App")

text = st.text_input("Enter your text:")

if text:
    doc = nlp(text)
    st.write("Number of tokens:", len(doc))
    st.write("Number of entities:", len(doc.ents))

    if len(doc.ents) == 0:
        st.write("The text is likely to be generated by AI.")
    else:
        st.write("The text is likely to be written by human.")
