import streamlit as st
from liwc import LIWC

liwc = LIWC()

st.title("LIWC Text Analysis App")

text = st.text_input("Enter your text:")

if text:
    result = liwc.analyze(text)
    st.write("Result:", result)
    if result['perceptron'] > 0.5:
        st.write("The text is likely to be generated by AI.")
    else:
        st.write("The text is likely to be written by human.")
