import streamlit as st
from gensim.summarization import summarize

st.title("Gensim Text Analysis App")

text = st.text_input("Enter your text:")

if text:
    summary = summarize(text)
    st.write("Original Text:")
    st.write(text)
    st.write("Summary:")
    st.write(summary)
    if len(summary) / len(text) > 0.9:
        st.write("The text is likely to be generated by AI.")
    else:
        st.write("The text is likely to be written by human.")
